on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Package code into .zip file
      run: |
        zip -r ChatGDP-DiscordBot.zip .
        
    - name: Upload code to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        args: --no-progress
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: elasticbeanstalk-us-west-1-431738351778
        source_dir: .
        destination_dir: .

    - name: Get the current version of the application
      run: |
        CURRENT_VERSION=$(aws elasticbeanstalk describe-application-versions \
        --application-name ChatGDP-DiscordBot \
        --query 'ApplicationVersions[-1].VersionLabel' \
        --output text)

    - name: Update the version label
      env:
        NEW_VERSION: v$(echo "$CURRENT_VERSION" | awk -F'.' '{printf "%d.%d.%d", $1, $2, $3 + 1}')

    - name: Create application version
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name ChatGDP-DiscordBot \
        --version-label $NEW_VERSION \
        --source-bundle S3Bucket=elasticbeanstalk-us-west-1-431738351778,S3Key=ChatGDP-DiscordBot.zip
    - name: Deploy application version
      run: |
        aws elasticbeanstalk update-environment \
        --environment-name Chatgdpdiscordbot-env-1 \
        --version-label $NEW_VERSION
    - name: Start Bot
      run: |
        node index.js
        echo $DISCORD_TOKEN

