name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download the zip file from S3
      run: aws s3 cp s3://chatgdp-discordbot/ChatGDP-DiscordBot.zip .

    - name: Unzip the file
      run: unzip ChatGDP-DiscordBot.zip

    - name: Install dependencies
      run: npm install

    - name: Start the bot
      run: node index.js
